-- Seed jobs aligned to UK Talent Link's stated practices & markets.
-- Idempotent: uses INSERT OR IGNORE keyed on id.

INSERT OR IGNORE INTO jobs
  (id, created_at, title, company, location, sector, seniority,
   min_years_experience, description, must_have_skills, nice_to_have_skills, status)
VALUES
  ('job_cfo_fin_london',
   1713830400000,
   'Chief Financial Officer',
   'Private UK Wealth Manager',
   'London',
   'Financial Services',
   'executive',
   15,
   'Retained search for CFO of a private UK wealth manager. FCA-regulated; reports to CEO and board. Leads finance, treasury, regulatory reporting, and IR.',
   '["finance leadership","fca regulation","board reporting","financial planning"]',
   '["wealth management","treasury","investor relations","mergers and acquisitions"]',
   'open'),

  ('job_hrd_tech_london',
   1713830400000,
   'HR Director',
   'Series C FinTech',
   'London',
   'Technology',
   'director',
   10,
   'Scale-up HRD covering TUPE integration after recent acquisition, UK employment law, remuneration, and org design across 400 staff.',
   '["human resources","employment law","tupe","organisational design","remuneration"]',
   '["fintech","scale-up experience","equity design"]',
   'open'),

  ('job_ged_energy_riyadh',
   1713830400000,
   'General Counsel — Energy',
   'Saudi Energy Major',
   'Riyadh',
   'Energy',
   'executive',
   18,
   'GC for upstream & midstream operations. Arabic desirable, English required. KSA residency supported.',
   '["corporate law","energy sector","contract negotiation","regulatory affairs"]',
   '["arabic","ksa experience","upstream oil and gas"]',
   'open'),

  ('job_head_digital_dubai',
   1713830400000,
   'Head of Digital Health',
   'GCC Health Platform',
   'Dubai',
   'Healthcare',
   'senior',
   8,
   'Own the digital product line for a regional health platform. Product, engineering, and data reporting into the CEO.',
   '["product management","healthcare","digital transformation","team leadership"]',
   '["gcc experience","telemedicine","data analytics"]',
   'open'),

  ('job_partner_consultancy_doha',
   1713830400000,
   'Partner — Strategy Consulting',
   'Boutique Consultancy',
   'Doha',
   'Professional Services',
   'executive',
   14,
   'Client-facing partner with a book of business in GCC public sector or banking. Joint practice lead role.',
   '["strategy consulting","client management","business development","financial services"]',
   '["public sector","gcc","arabic"]',
   'open'),

  ('job_head_retail_abudhabi',
   1713830400000,
   'Head of Retail Operations',
   'Regional Consumer Group',
   'Abu Dhabi',
   'Consumer & Retail',
   'senior',
   10,
   'Operational leadership across 120 retail outlets in the UAE. P&L responsibility, supply chain oversight.',
   '["retail operations","p&l management","supply chain","team leadership"]',
   '["uae experience","franchising","luxury retail"]',
   'open');
