// Preview data — used when Cloudflare D1 binding isn't available
// (Lovable preview, plain Vite dev). Production reads from D1.

import type { Lead, Candidate, ContentItem } from "../schemas";

const day = 86_400_000;
const t = (n: number) => Date.now() - n * day;

export const MOCK_LEADS: Lead[] = [
  {
    id: "lead_seed_001",
    created_at: t(2),
    updated_at: t(2),
    name: "Sarah Mitchell",
    company: "Meridian Logistics Ltd",
    email: "s.mitchell@meridian.co.uk",
    phone: "07712 334 891",
    service: "HR Consultancy",
    message:
      "We're a logistics company of 85 staff and need an HR audit plus updated employment contracts following recent tribunal changes.",
    score: 92,
    priority: "High",
    status: "New",
    ai_draft: null,
  },
  {
    id: "lead_seed_002",
    created_at: t(3),
    updated_at: t(3),
    name: "James Okafor",
    company: "Okafor & Partners",
    email: "james@okaforpartners.com",
    phone: "07845 221 003",
    service: "Employment Law",
    message:
      "One of our employees is claiming unfair dismissal. Need urgent legal guidance before the ET1 deadline next week.",
    score: 88,
    priority: "High",
    status: "Contacted",
    ai_draft: null,
  },
  {
    id: "lead_seed_003",
    created_at: t(4),
    updated_at: t(4),
    name: "Priya Sharma",
    company: "NovaTech Solutions",
    email: "priya.sharma@novatech.io",
    phone: "07920 441 772",
    service: "Recruitment",
    message:
      "Looking to hire 3 senior software engineers and a Head of Product. Middle East expansion coming in Q3.",
    score: 79,
    priority: "Medium",
    status: "Qualified",
    ai_draft: null,
  },
  {
    id: "lead_seed_004",
    created_at: t(5),
    updated_at: t(5),
    name: "Tom Westbury",
    company: "Self-employed",
    email: "tomwestbury@gmail.com",
    phone: "07633 118 200",
    service: "Employment Law",
    message: "Hi just wondering if you can help with IR35 question for my contract",
    score: 34,
    priority: "Low",
    status: "New",
    ai_draft: null,
  },
  {
    id: "lead_seed_005",
    created_at: t(6),
    updated_at: t(6),
    name: "Aisha Nkrumah",
    company: "Atlas Property Group",
    email: "a.nkrumah@atlasproperty.co.uk",
    phone: "07789 554 321",
    service: "HR Consultancy",
    message:
      "We're scaling from 30 to 90 staff over 18 months and need an outsourced HR partner to build the people infrastructure.",
    score: 96,
    priority: "High",
    status: "Proposal Sent",
    ai_draft: null,
  },
];

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: "cand_seed_001",
    created_at: t(10),
    updated_at: t(10),
    name: "David Chen",
    role: "Head of Finance",
    client: "Atlas Property Group",
    email: "d.chen@email.com",
    stage: "Shortlisted",
    score: 88,
    notes:
      "Strong CFO background, 12 yrs PE-backed firms. Slight overqualified concern.",
    ai_analysis: null,
  },
  {
    id: "cand_seed_002",
    created_at: t(8),
    updated_at: t(8),
    name: "Fatima Al-Rashid",
    role: "HR Director",
    client: "Meridian Logistics Ltd",
    email: "fatima.ar@email.com",
    stage: "Interview",
    score: 94,
    notes:
      "Exceptional. CIPD Level 7, logistics sector specific. Recommend fast-track.",
    ai_analysis: null,
  },
  {
    id: "cand_seed_003",
    created_at: t(5),
    updated_at: t(5),
    name: "Marcus Thompson",
    role: "Senior Engineer",
    client: "NovaTech Solutions",
    email: "m.thompson@email.com",
    stage: "Sourced",
    score: 71,
    notes: "React/Node stack matches. 5yrs exp. Available immediately.",
    ai_analysis: null,
  },
  {
    id: "cand_seed_004",
    created_at: t(6),
    updated_at: t(6),
    name: "Zara Patel",
    role: "Senior Engineer",
    client: "NovaTech Solutions",
    email: "zara.p@email.com",
    stage: "Shortlisted",
    score: 82,
    notes: "Strong TypeScript, AWS certified. Notice period 3 months.",
    ai_analysis: null,
  },
  {
    id: "cand_seed_005",
    created_at: t(12),
    updated_at: t(12),
    name: "Oliver Hughes",
    role: "Head of Finance",
    client: "Atlas Property Group",
    email: "o.hughes@email.com",
    stage: "Rejected",
    score: 58,
    notes: "Gaps in PE experience. Not progressing.",
    ai_analysis: null,
  },
  {
    id: "cand_seed_006",
    created_at: t(7),
    updated_at: t(7),
    name: "Kenji Watanabe",
    role: "Head of Product",
    client: "NovaTech Solutions",
    email: "k.watan@email.com",
    stage: "Offer",
    score: 91,
    notes:
      "Outstanding product sense, shipped 3 B2B SaaS products. Client loved him.",
    ai_analysis: null,
  },
];

export const MOCK_CONTENT: ContentItem[] = [
  {
    id: "cont_seed_001",
    created_at: t(10),
    title: "IR35 in 2026: What UK Contractors Must Know",
    type: "Blog Article",
    tone: "Professional & Authoritative",
    content:
      "# IR35 in 2026: What UK Contractors Must Know\n\nThe IR35 rules continue to shape how contractors operate in the UK...",
    word_count: 1240,
    published: true,
  },
  {
    id: "cont_seed_002",
    created_at: t(15),
    title: "5 Signs Your Business Needs an HR Audit",
    type: "Blog Article",
    tone: "Approachable & Plain-English",
    content:
      "# 5 Signs Your Business Needs an HR Audit\n\nMany growing businesses underestimate when their HR function needs review...",
    word_count: 980,
    published: true,
  },
  {
    id: "cont_seed_003",
    created_at: t(20),
    title: "Redundancy Process: A Step-by-Step Guide",
    type: "LinkedIn Post",
    tone: "Thought Leadership",
    content:
      "Redundancy is one of the most challenging processes employers face...",
    word_count: 310,
    published: true,
  },
];

export const MOCK_ANALYTICS = {
  visitors: [
    { month: "Nov", count: 820 },
    { month: "Dec", count: 940 },
    { month: "Jan", count: 1120 },
    { month: "Feb", count: 1380 },
    { month: "Mar", count: 1590 },
    { month: "Apr", count: 1840 },
  ],
  leads: [
    { month: "Nov", count: 8 },
    { month: "Dec", count: 12 },
    { month: "Jan", count: 15 },
    { month: "Feb", count: 19 },
    { month: "Mar", count: 23 },
    { month: "Apr", count: 28 },
  ],
  services: [
    { name: "HR Consultancy", value: 38 },
    { name: "Recruitment", value: 31 },
    { name: "Employment Law", value: 24 },
    { name: "Middle East Recruitment", value: 7 },
  ],
  funnel: [
    { stage: "Visitors", n: 1840 },
    { stage: "Form Started", n: 180 },
    { stage: "Submitted", n: 84 },
    { stage: "Leads", n: 84 },
    { stage: "Qualified", n: 31 },
    { stage: "Closed", n: 9 },
  ],
};
