// Preview/development fallback data used when Cloudflare bindings are unavailable
// (e.g. Lovable preview, plain Vite dev). Real D1/R2 data is used in production.

import type { CandidateRow, CandidateDetail, FaqTopic } from "./db";
import type { Job, Match } from "../schemas/job";

const now = Date.now();
const day = 86_400_000;

export const MOCK_CANDIDATES: CandidateRow[] = [
  {
    id: "cand_preview_001",
    created_at: now - 2 * day,
    updated_at: now - 2 * day,
    status: "parsed",
    source_filename: "sarah_okonkwo_cv.pdf",
    source_r2_key: "cvs/cand_preview_001/sarah_okonkwo_cv.pdf",
    name: "Sarah Okonkwo",
    email: "s.okonkwo@email.com",
    location: "London, UK",
    headline: "Chief Financial Officer | FCA-Regulated | Wealth Management",
    seniority: "executive",
    total_years_experience: 18,
    quality_score: 87,
  },
  {
    id: "cand_preview_002",
    created_at: now - 1 * day,
    updated_at: now - 1 * day,
    status: "parsed",
    source_filename: "james_harrington_cv.pdf",
    source_r2_key: "cvs/cand_preview_002/james_harrington_cv.pdf",
    name: "James Harrington",
    email: "j.harrington@email.com",
    location: "Dubai, UAE",
    headline: "HR Director | TUPE & Employment Law | FinTech Scale-ups",
    seniority: "director",
    total_years_experience: 12,
    quality_score: 74,
  },
  {
    id: "cand_preview_003",
    created_at: now - 4 * 3600_000,
    updated_at: now - 4 * 3600_000,
    status: "uploading",
    source_filename: "priya_sharma_resume.pdf",
    source_r2_key: null,
    name: null,
    email: null,
    location: null,
    headline: null,
    seniority: null,
    total_years_experience: null,
    quality_score: null,
  },
  {
    id: "cand_preview_004",
    created_at: now - 3 * day,
    updated_at: now - 3 * day,
    status: "failed",
    source_filename: "corrupted_file.pdf",
    source_r2_key: "cvs/cand_preview_004/corrupted_file.pdf",
    name: null,
    email: null,
    location: null,
    headline: null,
    seniority: null,
    total_years_experience: null,
    quality_score: null,
  },
];

export const MOCK_CANDIDATE_DETAILS: Record<string, CandidateDetail> = {
  cand_preview_001: {
    ...MOCK_CANDIDATES[0],
    phone: "+44 7700 900123",
    summary:
      "Sarah is a highly accomplished CFO with 18 years in FCA-regulated wealth management and private banking. She has led finance functions across three FTSE 250-adjacent firms, steering two through FCA supervision reviews and one through a £240m acquisition. She brings exceptional credibility at board level and a strong track record in treasury and investor relations.",
    work_authorization: "British Citizen — Right to Work UK/UAE",
    quality_notes: [
      "CV is well-structured and ATS-friendly.",
      "Quantified achievements are strong (e.g. £240m transaction).",
      "Consider adding a LinkedIn URL to improve recruiter verification.",
      "Education section could include graduation years.",
    ],
    links: { linkedin: null, github: null, portfolio: null },
    skills: [
      { skill: "finance leadership", skill_raw: "Finance Leadership", years_experience: 18 },
      { skill: "fca regulation", skill_raw: "FCA Regulatory Compliance", years_experience: 12 },
      { skill: "board reporting", skill_raw: "Board & Exec Reporting", years_experience: 10 },
      { skill: "financial planning", skill_raw: "Financial Planning & Analysis", years_experience: 15 },
      { skill: "treasury", skill_raw: "Treasury Management", years_experience: 8 },
      { skill: "investor relations", skill_raw: "Investor Relations", years_experience: 6 },
      { skill: "mergers and acquisitions", skill_raw: "M&A / Corporate Finance", years_experience: 5 },
    ],
    experience: [
      {
        company: "Meridian Private Wealth",
        title: "Chief Financial Officer",
        start_date: "2018-03",
        end_date: null,
        is_current: true,
        location: "London",
        description:
          "Led finance, treasury, regulatory capital reporting, and investor relations for a £1.2bn AUM wealth manager. Managed FCA supervisory visits and steered firm through IFPR implementation.",
      },
      {
        company: "Cavendish Asset Management",
        title: "Finance Director",
        start_date: "2013-06",
        end_date: "2018-02",
        is_current: false,
        location: "London",
        description:
          "Finance Director across UK and Guernsey entities. Led £240m cross-border acquisition integration.",
      },
      {
        company: "Barclays Wealth",
        title: "Head of Financial Control",
        start_date: "2007-09",
        end_date: "2013-05",
        is_current: false,
        location: "London",
        description: "Financial control and management reporting for UK HNW book.",
      },
    ],
    education: [
      {
        institution: "London School of Economics",
        degree: "BSc",
        field: "Accounting & Finance",
        start_year: "2001",
        end_year: "2004",
      },
      {
        institution: "ICAEW",
        degree: "ACA",
        field: "Chartered Accountancy",
        start_year: "2004",
        end_year: "2007",
      },
    ],
    score_breakdown: null,
    improvement_report: null,
    parse_error: null,
  },
  cand_preview_002: {
    ...MOCK_CANDIDATES[1],
    phone: "+971 50 234 5678",
    summary:
      "James is a senior HR leader with 12 years' experience across UK employment law, TUPE integrations, and people strategy in high-growth FinTech businesses. Currently based in Dubai with full UK right to work, he combines deep legal grounding with operational delivery across 400-person organisations.",
    work_authorization: "British Citizen — UK & UAE work authorisation",
    quality_notes: [
      "Strong on employment law specifics — good for UKTL mandates.",
      "Add metrics to org design bullet points (e.g. headcount managed, cost saved).",
      "LinkedIn profile URL missing.",
    ],
    links: { linkedin: null, github: null, portfolio: null },
    skills: [
      { skill: "human resources", skill_raw: "HR Strategy & Leadership", years_experience: 12 },
      { skill: "employment law", skill_raw: "UK Employment Law", years_experience: 10 },
      { skill: "tupe", skill_raw: "TUPE Transfers", years_experience: 7 },
      { skill: "organisational design", skill_raw: "Organisational Design", years_experience: 8 },
      { skill: "remuneration", skill_raw: "Remuneration & Benefits", years_experience: 6 },
      { skill: "equity design", skill_raw: "Equity / Options Design", years_experience: 3 },
    ],
    experience: [
      {
        company: "PayAxis (FinTech)",
        title: "HR Director",
        start_date: "2020-01",
        end_date: null,
        is_current: true,
        location: "Dubai / London",
        description:
          "HRD for 420-person Series C FinTech. Led post-acquisition TUPE integration of 80 staff, redesigned grading framework, and built equity participation scheme.",
      },
      {
        company: "LegalPay Ltd",
        title: "Head of People",
        start_date: "2016-04",
        end_date: "2019-12",
        is_current: false,
        location: "London",
        description:
          "Built the people function from scratch. Managed employment tribunal risk and delivered first company-wide pay review.",
      },
    ],
    education: [
      {
        institution: "University of Warwick",
        degree: "LLB",
        field: "Law",
        start_year: "2007",
        end_year: "2010",
      },
      {
        institution: "CIPD",
        degree: "Level 7",
        field: "Human Resource Management",
        start_year: "2012",
        end_year: "2013",
      },
    ],
    score_breakdown: null,
    improvement_report: null,
    parse_error: null,
  },
};

export const MOCK_JOBS: Job[] = [
  {
    id: "job_cfo_fin_london",
    created_at: now - 20 * day,
    title: "Chief Financial Officer",
    company: "Private UK Wealth Manager",
    location: "London",
    sector: "Financial Services",
    seniority: "executive",
    min_years_experience: 15,
    description:
      "Retained search for CFO of a private UK wealth manager. FCA-regulated; reports to CEO and board. Leads finance, treasury, regulatory reporting, and IR.",
    must_have_skills: ["finance leadership", "fca regulation", "board reporting", "financial planning"],
    nice_to_have_skills: ["wealth management", "treasury", "investor relations", "mergers and acquisitions"],
    status: "open",
  },
  {
    id: "job_hrd_tech_london",
    created_at: now - 20 * day,
    title: "HR Director",
    company: "Series C FinTech",
    location: "London",
    sector: "Technology",
    seniority: "director",
    min_years_experience: 10,
    description:
      "Scale-up HRD covering TUPE integration after recent acquisition, UK employment law, remuneration, and org design across 400 staff.",
    must_have_skills: ["human resources", "employment law", "tupe", "organisational design", "remuneration"],
    nice_to_have_skills: ["fintech", "scale-up experience", "equity design"],
    status: "open",
  },
  {
    id: "job_ged_energy_riyadh",
    created_at: now - 20 * day,
    title: "General Counsel — Energy",
    company: "Saudi Energy Major",
    location: "Riyadh",
    sector: "Energy",
    seniority: "executive",
    min_years_experience: 18,
    description:
      "GC for upstream & midstream operations. Arabic desirable, English required. KSA residency supported.",
    must_have_skills: ["corporate law", "energy sector", "contract negotiation", "regulatory affairs"],
    nice_to_have_skills: ["arabic", "ksa experience", "upstream oil and gas"],
    status: "open",
  },
  {
    id: "job_head_digital_dubai",
    created_at: now - 20 * day,
    title: "Head of Digital Health",
    company: "GCC Health Platform",
    location: "Dubai",
    sector: "Healthcare",
    seniority: "director",
    min_years_experience: 8,
    description:
      "Lead digital product strategy across a GCC-wide health platform. P&L ownership, cross-functional team leadership, UAE residency supported.",
    must_have_skills: ["digital health", "product strategy", "p&l management", "stakeholder management"],
    nice_to_have_skills: ["gcc experience", "health tech", "agile"],
    status: "open",
  },
];

export const MOCK_MATCHES_BY_CANDIDATE: Record<string, (Match & { job?: { id: string; title: string; company: string | null } })[]> = {
  cand_preview_001: [
    {
      candidate_id: "cand_preview_001",
      job_id: "job_cfo_fin_london",
      score: 92,
      skills_overlap: 95,
      experience_fit: 95,
      seniority_fit: 100,
      location_fit: 100,
      matched_skills: ["finance leadership", "fca regulation", "board reporting", "financial planning", "treasury", "investor relations"],
      missing_skills: [],
      reasoning: "Exceptional fit. All four must-have skills matched with senior depth. 18 years exceeds the 15-year threshold. Executive seniority and London location are exact matches.",
      computed_at: now - 2 * day,
      job: { id: "job_cfo_fin_london", title: "Chief Financial Officer", company: "Private UK Wealth Manager" },
    },
    {
      candidate_id: "cand_preview_001",
      job_id: "job_hrd_tech_london",
      score: 18,
      skills_overlap: 10,
      experience_fit: 85,
      seniority_fit: 50,
      location_fit: 100,
      matched_skills: [],
      missing_skills: ["human resources", "employment law", "tupe", "organisational design"],
      reasoning: "Background is finance, not HR. Skills and function are not aligned to this mandate.",
      computed_at: now - 2 * day,
      job: { id: "job_hrd_tech_london", title: "HR Director", company: "Series C FinTech" },
    },
  ],
  cand_preview_002: [
    {
      candidate_id: "cand_preview_002",
      job_id: "job_hrd_tech_london",
      score: 89,
      skills_overlap: 95,
      experience_fit: 90,
      seniority_fit: 100,
      location_fit: 80,
      matched_skills: ["human resources", "employment law", "tupe", "organisational design", "remuneration", "equity design"],
      missing_skills: [],
      reasoning: "All must-have skills matched. 12 years exceeds the 10-year minimum. Director seniority is exact. Currently Dubai-based but has stated UK availability.",
      computed_at: now - 1 * day,
      job: { id: "job_hrd_tech_london", title: "HR Director", company: "Series C FinTech" },
    },
  ],
};

export const MOCK_MATCHES_BY_JOB: Record<string, (Match & { candidate?: { id: string; name: string | null; headline: string | null } })[]> = {
  job_cfo_fin_london: [
    {
      candidate_id: "cand_preview_001",
      job_id: "job_cfo_fin_london",
      score: 92,
      skills_overlap: 95,
      experience_fit: 95,
      seniority_fit: 100,
      location_fit: 100,
      matched_skills: ["finance leadership", "fca regulation", "board reporting", "financial planning", "treasury"],
      missing_skills: [],
      reasoning: "Exceptional fit across all four scoring dimensions.",
      computed_at: now - 2 * day,
      candidate: { id: "cand_preview_001", name: "Sarah Okonkwo", headline: "Chief Financial Officer | FCA-Regulated" },
    },
  ],
  job_hrd_tech_london: [
    {
      candidate_id: "cand_preview_002",
      job_id: "job_hrd_tech_london",
      score: 89,
      skills_overlap: 95,
      experience_fit: 90,
      seniority_fit: 100,
      location_fit: 80,
      matched_skills: ["human resources", "employment law", "tupe", "organisational design", "remuneration"],
      missing_skills: [],
      reasoning: "All must-have skills matched. Strong FinTech HR background.",
      computed_at: now - 1 * day,
      candidate: { id: "cand_preview_002", name: "James Harrington", headline: "HR Director | TUPE & Employment Law" },
    },
  ],
  job_ged_energy_riyadh: [],
  job_head_digital_dubai: [],
};

export const MOCK_FAQ_TOPICS: FaqTopic[] = [
  {
    id: "faq_unfair_dismissal",
    title: "Unfair Dismissal — What Are My Rights?",
    category: "dismissal",
    keywords: ["dismiss", "dismissal", "fired", "sacked", "unfair", "termination", "let go", "notice", "tribunal"],
    sector_tag: null,
    video_url: null,
    thumbnail: null,
    duration_s: 312,
    published: 1,
    view_count: 142,
    created_at: now - 30 * day,
  },
  {
    id: "faq_zero_hours",
    title: "Zero Hours Contracts — Your Rights Explained",
    category: "contracts",
    keywords: ["zero hours", "zero-hours", "contract", "guaranteed hours", "casual", "on-call", "flexible"],
    sector_tag: null,
    video_url: null,
    thumbnail: null,
    duration_s: 278,
    published: 1,
    view_count: 97,
    created_at: now - 28 * day,
  },
  {
    id: "faq_discrimination",
    title: "Workplace Discrimination — Protected Characteristics",
    category: "discrimination",
    keywords: ["discrimination", "harass", "harassment", "protected", "equality", "race", "gender", "disability", "religion", "age", "bullying"],
    sector_tag: null,
    video_url: null,
    thumbnail: null,
    duration_s: 355,
    published: 1,
    view_count: 88,
    created_at: now - 25 * day,
  },
  {
    id: "faq_minimum_wage",
    title: "National Minimum Wage — Am I Being Paid Correctly?",
    category: "pay",
    keywords: ["minimum wage", "national living wage", "underpaid", "pay", "salary", "wage", "nmw", "nlw", "hourly rate"],
    sector_tag: null,
    video_url: null,
    thumbnail: null,
    duration_s: 224,
    published: 1,
    view_count: 203,
    created_at: now - 22 * day,
  },
  {
    id: "faq_redundancy",
    title: "Redundancy — Process, Pay, and Your Rights",
    category: "redundancy",
    keywords: ["redundancy", "redundant", "made redundant", "statutory redundancy pay", "selection", "collective", "consultation", "TUPE"],
    sector_tag: null,
    video_url: null,
    thumbnail: null,
    duration_s: 418,
    published: 1,
    view_count: 176,
    created_at: now - 20 * day,
  },
  {
    id: "faq_holiday_entitlement",
    title: "Holiday Entitlement — How Much Are You Owed?",
    category: "holiday",
    keywords: ["holiday", "annual leave", "paid leave", "entitlement", "bank holiday", "statutory leave"],
    sector_tag: null,
    video_url: null,
    thumbnail: null,
    duration_s: 196,
    published: 1,
    view_count: 115,
    created_at: now - 18 * day,
  },
  {
    id: "faq_working_time",
    title: "Working Hours — The 48-Hour Week and Rest Breaks",
    category: "working-time",
    keywords: ["working hours", "48 hour", "overtime", "rest break", "rest period", "opt out", "night work", "working time regulations"],
    sector_tag: null,
    video_url: null,
    thumbnail: null,
    duration_s: 261,
    published: 1,
    view_count: 79,
    created_at: now - 15 * day,
  },
  {
    id: "faq_maternity",
    title: "Maternity & Paternity Leave — Entitlements and Pay",
    category: "leave",
    keywords: ["maternity", "paternity", "parental leave", "shared parental leave", "smp", "pregnancy", "adoption", "baby"],
    sector_tag: null,
    video_url: null,
    thumbnail: null,
    duration_s: 344,
    published: 1,
    view_count: 134,
    created_at: now - 12 * day,
  },
  {
    id: "faq_whistleblowing",
    title: "Whistleblowing — Protected Disclosure Rights",
    category: "whistleblowing",
    keywords: ["whistleblowing", "whistleblower", "report", "disclosure", "protected disclosure", "public interest", "detriment", "malpractice"],
    sector_tag: null,
    video_url: null,
    thumbnail: null,
    duration_s: 287,
    published: 1,
    view_count: 52,
    created_at: now - 10 * day,
  },
  {
    id: "faq_settlement",
    title: "Settlement Agreements — What You Need to Know",
    category: "settlement",
    keywords: ["settlement", "settlement agreement", "compromise", "ex gratia", "payment", "sign away", "legal advice", "ACAS conciliation"],
    sector_tag: null,
    video_url: null,
    thumbnail: null,
    duration_s: 332,
    published: 1,
    view_count: 63,
    created_at: now - 7 * day,
  },
  {
    id: "faq_cis_construction",
    title: "Construction Industry Scheme — Employment Status",
    category: "contracts",
    keywords: ["CIS", "construction industry scheme", "subcontractor", "self-employed", "employed", "employment status", "IR35", "construction"],
    sector_tag: "construction",
    video_url: null,
    thumbnail: null,
    duration_s: 298,
    published: 1,
    view_count: 41,
    created_at: now - 5 * day,
  },
  {
    id: "faq_tech_ip",
    title: "Intellectual Property at Work — Who Owns Your Code?",
    category: "contracts",
    keywords: ["intellectual property", "IP", "code", "software", "invention", "copyright", "invention", "ownership", "technology", "developer"],
    sector_tag: "technology",
    video_url: null,
    thumbnail: null,
    duration_s: 243,
    published: 1,
    view_count: 29,
    created_at: now - 3 * day,
  },
];
